<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <?php echo $data1; ?> <hr />
    <?=$data1; ?> <hr />

    <?php if ($data2['sex'] == '男') : ?>
        强大的男人
    <?php else: ?>
        弱小的女人
    <?php endif; ?>
    <hr/>
    <?php foreach ($data3 as $temp) : ?>
        <?=$temp['name']; ?>
        <?=$temp['age']; ?>
        <?=$temp['sex']; ?>
        <br/>
    <?php endforeach; ?>

</body>
</html>